### ISSUE TITLE
三级及以上级联无序列表内的资源无法通过链接下载

### ISSUE THREAD

**Issue by HLXY-420** [bjut-swift/BJUT-Helper#11]
三级及以上级联无序列表内的资源链接，生成的URL点击后会在URL中间生成%5C字符，从而导致找不到对应资料网址而跳转至GitHub 404页面，例如：
<img width="521" alt="image" src="https://github.com/bjut-swift/BJUT-Helper/assets/73209424/8536e566-1635-4a1e-8df3-9ef101344c6c">
点击后会跳转到的URL为：https://github.com/bjut-swift/BJUT-Helper/raw/master/微机原理与接口技术%5C微机2016期末考试/1.jpg
其中的%5C字符会导致URL解析错误，定向到404页面。
受此问题影响的页面包括：
微机原理与接口技术、毛概、电工技术I、电工电子技术、电路分析基础、高等数学

**Comment by Nagi-ovo** [comment]
感谢！
